### PR TITLE
Highly experimental implementation of SubTableListColumns

### PR DESCRIPTION
**Pull request by spenczar**
This adds a new column type, `SubTableListColumn`, which can be used to store a list of tables in each row of a quivr table. It's a fairly heady concept, and comes with some caveats and many advisory notes.

It looks like this in practice:

```py
class GnomonicTransformTable(qv.Table):
    ephems = orbits.Ephemeris.as_column()
    test_orbit_states = orbits.Orbits.as_column()
    exposures = exposures.Exposures.as_column()
    detections = qv.SubTableListColumn(detections.PointSourceDetections)

gtt = GnomonicTransformTable.from_kwargs(
    ephems=...,
    test_orbit_states=...,
    exposures=...,
    detections=[
        PointSourceDetections.from_kwargs(...),
        PointSourceDetections.from_kwargs(...),
        PointSourceDetections.from_kwargs(...),
    ],
)

# the associated instance attribute is a *list*, not a pyarrow array.
assert isinstance(gtt.detections, list)
# Each element in the list is a Table instance:
print(gtt.detections[0])
# PointSourceDetections(size=10)
```

### Known limitations:

1. All attributes must be identical for all entries in the list, including for any nested sub-tables, and sub-lists-of-sub-tables.
2. You can't make a List-of-lists-of-tables.
3. You can't make extra large lists of tables - that is, no more than 2**31 entries.
4. When using `from_kwargs` to construct the value for a SubTableListColumn, you must pass in a Python `list` of `qv.Table`s. Pyarrow arrays aren't allowed, nor numpy arrays, or pandas series, etc. Just lists.

### Warnings 

1. I suspect there are probably bugs to do with nullable fields and non-nullable tables. Something like this is probably not very coherent:
   ```py
   class NonNullablePair(qv.Table):
       x = qv.Int64Column()
   
   class Wrapper(qv.Table):
       pairs = qv.SubTableListColumn(NonNullablePair, nullable=True)
   ```
2. I have not tested serialization to/from anything.
3. I have no idea what this will look like in a dataframe.
5. I don't think default values will work. I'm not even sure how they _should_ work.

### CODE REVIEW

**Comment by moeyensj** [comment]
I'm going to create an experimental branch in [https://www.github.com/B612-Asteroid-Insitute/adam_core](adam_core) to replace the linkages for ephemeris with a SubTableListColumn implementation. I'll report back with my thoughts.

**Comment by moeyensj** [comment]
Couple thoughts as I'm working on this:
1. It's not obvious in what direction many-to-one or one-to-many relationships should be expressed. I suppose it depends on the use case. Here is an example:

For ephemeris: what feels the most natural is to have a table that contains for each orbit a list of predicted ephemerides as viewed from observers. In this instance, you will end up having repeated observer coordinate values. To avoid that, you might then instead make a table with unique observers and for each unique observer you have a list of ephemerides for the orbits at that time (like the current linkages are structured). The latter is going to be more cumbersome to use for things like orbit determination where you really just want ephemerides and observer positions for a single object at any time. But the latter is better for memory efficiency (less duplication), and for things where we might want to analysis in windows of time. 

2. Specifying a uniqueness constraint on a column seems like a feature that would need to be added. 

Going back to the ephemeris example. If I decide to have each row in the table belong to a unique orbit (and have ephemerides and observers as lists of tables), then being able to set `unique=True` on the `orbit_id = qv.StringColumn` would make that kind of a relationship more explicit.

**Comment by moeyensj** [comment]
If we go the route of each row belongs to a unique orbit and we are okay with data duplication then the power of quivr still comes to our aid since we can just attached convenience functions to the ephemeris class:

```python
class Ephemeris(qv.Table):

    orbit_id = qv.StringColumn(nullable=False)
    object_id = qv.StringColumn()
    coordinates = qv.SubTableListColumn(coordinates.SphericalCoordinates)
    observers = qv.SubTableListColumn(observers.Observers)

    def select_observatory_code(self, observatory_code: str) -> Self: 
        pass


    def select_time_range(self, min_time: Time, max_time: Time) -> Self:
        pass
```

**Comment by spenczar** [comment]
> It's not obvious in what direction many-to-one or one-to-many relationships should be expressed. I suppose it depends on the use case.

Yes. Table structure like this is always challenging in relational work. I don't think there's a simple answer.

It's quite possible that the right answer here will be to do a better job on linkages, supporting operations that link a chain of tables together.... I think we'll have to forge on with some experimentation (as you're doing, thanks!).

**Comment by spenczar** [comment]
I've decided not to pursue this. We may revisit.

**Pull request closed without merging**
